### ISSUE TITLE
response_fitter.py error

### ISSUE THREAD

**Issue by PaulGeha** [VU-Cog-Sci/response_fytter#36]
Hello, 
I am trying to use nideconv.  I started first with the example online here : https://nideconv.readthedocs.io/en/latest/ .  I keep getting an error message related to rf.plot_model_fit() as below.  I created a nideconv environment as can be seen in my home directory but I still cannot resolve the panda's dependency (it seems!). My understanding is that the version of panda needed is in there.   e 
 What is the fix for this? 

Thanks for any help you can provide

best
Paul
----------------------------

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/urmc-sh.rochester.edu/pgeha/nideconv_env/lib/python3.11/site-packages/nideconv/response_fitter.py", line 499, in plot_model_fit
    signal = self.get_original_signal(melt=True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/urmc-sh.rochester.edu/pgeha/nideconv_env/lib/python3.11/site-packages/nideconv/response_fitter.py", line 484, in get_original_signal
    .melt(var_name='roi',
     ^^^^^^^^^^^^^^^^^^^^
  File "/home/urmc-sh.rochester.edu/pgeha/nideconv_env/lib/python3.11/site-packages/pandas/core/frame.py", line 9942, in melt
    return melt(
           ^^^^^
  File "/home/urmc-sh.rochester.edu/pgeha/nideconv_env/lib/python3.11/site-packages/pandas/core/reshape/melt.py", line 54, in melt
    raise ValueError(
ValueError: value_name (signal) cannot match an element in the DataFrame columns.

**Comment by gjheij** [comment]
Hi Paul,

Indeed, I've noticed that some of the functions start to break down with newer versions of `pandas`. I've done most of my analysis based on `nideconv` using `pandas==1.5.3`, meaning it's incompatible with `python>3.10`.

I've started going through the code to correct some of these issues, but haven't seem this one yet. If you have `nideconv` installed using `pip install -e .`, you could delve into the functions to see if you can fix the problems.

In the meantime, you could have a look at [some of the functions I have wrapper around `nideconv`](https://github.com/gjheij/LazyPlot/blob/main/lazyplot/fitting.py) to extract predictions, time courses, and profiles.

Best,
Jurjen

**Comment by gjheij** [comment]
The input data has a column called `signal`. During the plotting with `plot_model_fit`, the `melt` function tried to add another column called `signal`. This is apparently not allowed, so I changed it to `signals`..
